export const Questions = [
    {
        prompt: "What is 1+3?",
        optionA: "24",
        optionB: "21",
        optionC: "4",
        optionD: "2",
        answer: "C",
    },
    {
        prompt: "Which is a stream platform?",
        optionA: "Twitter",
        optionB: "Twitch",
        optionC: "Google",
        optionD: "RobinHood",
        answer: "B",
    },
    {
        prompt: "Best tech youtube channel?",
        optionA: "Pedrotech",
        optionB: "Dev ed",
        optionC: "Fireship",
        optionD: "TechWithTim",
        answer: "A",
    },
    {
        prompt: "What is 6+4?",
        optionA: "24",
        optionB: "10",
        optionC: "4",
        optionD: "2",
        answer: "B",
    },
    {
        prompt: "Best Portugal soccer team",
        optionA: "Porto",
        optionB: "Benfica",
        optionC: "Sporting",
        optionD: "Braga",
        answer: "A",
    },
    {
        prompt: "Which language has the more native speakers?",
        optionA: "English",
        optionB: "Spanish",
        optionC: "Portugues",
        optionD: "French",
        answer: "B",
    },
    {
        prompt: "What is the most common surname in the United States?",
        optionA: "Biden",
        optionB: "Lopez",
        optionC: "Jhonson",
        optionD: "Smith",
        answer: "D",
    },
    {
        prompt: "Who was the Ancient Greek God of the Sun?",
        optionA: "Poseidon",
        optionB: "Zeus",
        optionC: "Apollo",
        optionD: "Artemis",
        answer: "C",
    },
    {
        prompt: "How many minutes are in a full week?",
        optionA: "16,987",
        optionB: "10,080",
        optionC: "9,567",
        optionD: "11,098",
        answer: "B",
    },
    {
        prompt: "What country drinks the most coffee per capita?",
        optionA: "Portugal",
        optionB: "Colombia",
        optionC: "Spain",
        optionD: "Finland",
        answer: "D",
    },
    {
        prompt: "What city is known as \"The Eternal City\"?",
        optionA: "Paris",
        optionB: "Rome",
        optionC: "New York",
        optionD: "London",
        answer: "B",
    },
    {
        prompt: "What country has won the most World Cups?",
        optionA: "Brazil",
        optionB: "Argentina",
        optionC: "Ingland",
        optionD: "France",
        answer: "A",
    },
    {
        prompt: "In what country is the Chernobyl nuclear plant located?",
        optionA: "Poland",
        optionB: "Bielorussia",
        optionC: "Russia",
        optionD: "Ukraine",
        answer: "D",
    },
    {
        prompt: "In what country was Elon Musk born?",
        optionA: "Germany",
        optionB: "Canada",
        optionC: "South Africa",
        optionD: "USA",
        answer: "C",
    },
    {
        prompt: "How many hearts does an octopus have?",
        optionA: "4",
        optionB: "3",
        optionC: "2",
        optionD: "1",
        answer: "B",
    },
    {
        prompt: "What planet is closest to the sun?",
        optionA: "Saturn",
        optionB: "Mercury",
        optionC: "Jupiter",
        optionD: "Earth",
        answer: "B",
    },
    {
        prompt: "Where did sushi originate?",
        optionA: "China",
        optionB: "Japon",
        optionC: "Malasia",
        optionD: "Korea",
        answer: "A",
    },
    {
        prompt: "What color are Mickey Mouse's shoes?",
        optionA: "Red",
        optionB: "Black",
        optionC: "Yellow",
        optionD: "White",
        answer: "C",
    },
];